user:
  name:
    maximum: 50
  email:
    maximum: 255
  pass:
    minimum: 6
helper:
  session:
    one: "1"
question:
  model:
    content:
      maximum: 200
  controller:
    check:
      one: "1"
answer:
  content:
    maximum: 200
paginate:
  default: 10
